---
- name: Install same tools on target hosts
  hosts: localhost
  become: true
  #vars:

  tasks:
    - import_role:
        name: ssh-keygen

- name: Install same tools on target hosts
  hosts: ansible_docker_serveur_web_1
  become: true
  #vars:

  tasks:
    - import_role:
        name: users
    - import_role:
        name: nginx

