
- name: ansible-playbook

  hosts: cibles

  become: true #Elévation des privilèges

  tasks:

  - name: Example from an Ansible Playbook

    ansible.builtin.ping:

 

  - name: Induce an exception to see what happens

    ansible.builtin.ping:

      data: crash
