---
# tasks file for nginx
- name: install nginx
  apt:
    name: nginx
    state: present
    cache_valid_time: 3600

- name: install vhost
  template:
    src: default_vhost.conf.j2
    dest: /etc/nginx/sites-available/default_vhost.conf
    owner: root
    group: root
    mode: 0644

