---

- name: first_playbook
  hosts: host1
  tasks:
  - name: create file 
    file:
     dest: /home/ansible/fic1
     state: touch 
    tags: 
     - create

  - name: delete
    file:
     dest: /home/ansible/fic11
     state: absent
    tags:
     - delete
